name: Run E2E tests

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Intalll nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Unitary tests
        run: npm run test --all

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          HOST: http://localhost:3000
          API_TOKEN: ${{ secrets.API_TOKEN }}
